### ISSUE TITLE
[BUG] seasonal mods don't work

### ISSUE THREAD

**Issue by stepmine** [The-Animonculory/Animonculory-Visual-Overhaul#4]
I've tried using seasonal mods with AVO and they don't seem to work with it, even though they work with other modlists.  I added Seasons of Skyrim. Turn of the Seasons and seasonal landscapes along with select your season for testing purposes.  When I start a new game with no other mods running and change the season to Winter, there is no change to the surroundings

**Comment by Althro** [comment]
This is not a bug. Please read the mod-pages on how to setup seasons. You will need to regenerate the lods and remove some mods relating to landscapes as otherwise they will not work. For a guide on how to do lods, please see our guide on doing them: https://github.com/The-Animonculory/Modding-Resources/blob/main/DynDOLOD.md
